language: python
install: pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python testinit.py
  - py.test ./tests/script.py
deploy:
  provider: heroku
  api_key:
    secure: U2AARC0FG/zHJBORbuFRpwHxLgv+4YotTvNL+UYT+zHcZkD/0IOPn/EiNXuYLLOC+dzY+1ESIRIgB6GJ8UsFY4+SbhzxKAuoTiq3OdLJW4fQ3awADrDcsGVPkPJ4ptEmqQxXB9mBUha+1GNalJyMhnqqjQ2loi7Eir5Dokzwe0vkjv/iE7jR7z3AoErBXrO9SWhJmrTIP1Mn6pVS5JrAHEu9tKvkz5+IfcrUuWxn1tHydcBbMBDCDo0ESRyqDlX5kAA4Utzu5cFMYyM/7vPDH0Cx5zHMNyN0iCIFfybYWn8NmFM1iQSLZQI6c8Yq6b8g0E25Nz27wQVG4+F7qx8D714CvJtrV5O1QYApEnf6G9fXD6KTlRxtDE0sZJNkbI9cJ7GYC+QtPcyG1SE7kGcEBT28w19tyb2d32fivC0O8mlf+PmwJiXfZLNf9vdccXlm26BWoS9i9vNN9adX5ylhm9fLyvGAY+2xx6w2uii22tLgTqM9Q+LNskUmh5sqPsADJao3GrkrOYXJkQZRmISJsY7Q4tLbxr/BxW1Vu7KDjShPprw5ywYq9gdEg3bs5j0SAxD8oovFYas07rT/DcvApt5rxrT/ndzT6AIsmEvk8ZavaHFP0qPpbtC7HovylE7NdSn6myW8DaK0jnoD6eQ1XCnfCvEPHD+rEUlX9qtKlGA=
  app: mysterious-reef-20098
